---
abstract: 'Parse mime-types, match against media ranges'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  File::Basename: 0
  JSON::XS: 0
  List::Util: 0
  Test::More: 0
  TestParseMIME: 0
  constant: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-MIME
requires:
  Exporter: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/Parse-MIME/issues
  homepage: http://github.com/ap/Parse-MIME
  repository: git://github.com/ap/Parse-MIME
version: 1.000
